# Generated by Django 3.1.3 on 2020-12-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='main/static/main/imgs/item-pictures')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=30)),
                ('sold_qty', models.IntegerField()),
                ('available_qty', models.IntegerField()),
            ],
        ),
    ]
