# Generated by Django 3.1.3 on 2020-12-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201207_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(upload_to='static/item-pictures'),
        ),
    ]
