# Generated by Django 3.1.3 on 2020-12-19 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
