# Generated by Django 3.1.3 on 2021-01-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_item_quantity'),
        ('main', '0005_booking'),
    ]

    operations = [
    ]
