# Generated by Django 3.1.3 on 2020-12-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=120)),
                ('LastName', models.CharField(max_length=120)),
                ('Number', models.IntegerField(max_length=20)),
            ],
        ),
    ]
