# Generated by Django 3.1.3 on 2020-12-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201207_1448'),
        ('shoppingcart', '0002_auto_20201213_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('clients', models.ManyToManyField(to='shoppingcart.client')),
                ('products', models.ManyToManyField(to='main.Item')),
            ],
        ),
    ]
