# Generated by Django 3.1.3 on 2020-12-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0007_auto_20201220_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='session',
            field=models.CharField(default='IDK', max_length=2000),
            preserve_default=False,
        ),
    ]
