# Generated by Django 3.1.3 on 2020-12-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0008_auto_20201220_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='subtotal',
            field=models.IntegerField(default=1),
        ),
    ]
