# Generated by Django 3.1.3 on 2021-01-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0009_orderitem_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Address',
            field=models.CharField(default='  ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.FloatField(default=1),
        ),
    ]
