# Generated by Django 3.1.3 on 2021-01-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0013_auto_20210106_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Orders',
            field=models.ManyToManyField(to='shoppingcart.Order'),
        ),
    ]
