# Generated by Django 3.1.3 on 2021-01-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0014_auto_20210110_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='STATUS',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Sold', 'Sold')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Orders',
            field=models.ManyToManyField(to='shoppingcart.Order'),
        ),
    ]
