# Generated by Django 3.1.3 on 2021-01-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0015_auto_20210110_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='session',
            new_name='OrderNumber',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='session',
            new_name='OrderNumber',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Orders',
            field=models.ManyToManyField(to='shoppingcart.Order'),
        ),
    ]
